version: '2'
services:
    web:
        build: .
        ports:
            - "3030:3030"
        volumes:
            - .:/usr/src/app
        depends_on:
            - db
        environment:
            PORT: 3030
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: massive
            POSTGRES_PASSWORD: science
            POSTGRES_DB: massivedb
        
