version: '2'
services:
    webpack:
        build:
            context: .
            dockerfile: tools/webpack.dockerfile
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules/
        environment:
            - NODE_ENV=development
    feathers:
        build:
            context: .
            dockerfile: tools/feathers.dockerfile
        ports:
            - "3030:3030"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules/
        depends_on:
            - postgres
            - redis
        environment:
            - PORT=3030
            - TMPDIR=/tmp
            - NODE_ENV=development
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - redis:/data
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=massive
            - POSTGRES_PASSWORD=science
            - POSTGRES_DB=massivedb
volumes:
    postgres:
    redis:
