version: '2'
services:
    webpack:
        build:
            context: .
            dockerfile: Dockerfile.webpack
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules/
    feathers:
        build:
            context: .
            dockerfile: Dockerfile.feathers
        ports:
            - "3030:3030"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules/
        depends_on:
            - postgres
            - redis
        environment:
            PORT: 3030
    redis:
        image: redis
        ports:
            - "6379:6379"
        depends_on:
            - postgres
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: massive
            POSTGRES_PASSWORD: science
            POSTGRES_DB: massivedb
