version: '2'
services:
    feathers:
        build:
            context: .
            dockerfile: Dockerfile.feathers.production
        ports:
            - "3030:3030"
        depends_on:
            - postgres
            - redis
        environment:
            PORT: 3030
    redis:
        image: redis
        ports:
            - "6379"
        depends_on:
            - postgres
    postgres:
        image: postgres
        ports:
            - "5432"
        environment:
            POSTGRES_USER: massive
            POSTGRES_PASSWORD: science
            POSTGRES_DB: massivedb
